language: go

matrix:
 include:
    - os: linux
      dist: trusty
      go: 1.8.x
      script:
        - go get github.com/golang/lint/golint
        - make build   
        - make lint      
        - make check
        - make coverage        
       
    - os: linux
      dist: trusty
      go: 1.9.x
      script:
        - go get github.com/golang/lint/golint     
        - make build        
        - make lint
        - make check
        - make coverage     
        
